<?php

namespace App\Models;

use App\Events\RecommendationCreated;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * TripRecommendation Model
 *
 * Stores AI-generated recommendations for trips.
 * Tracks acceptance status and can be converted to itinerary items.
 *
 * @property int $id
 * @property int $trip_id
 * @property int|null $chat_session_id
 * @property int|null $user_id
 * @property string $recommendation_type
 * @property string $source
 * @property array $data
 * @property float|null $confidence_score
 * @property string $status
 */
class TripRecommendation extends Model
{
    use HasFactory;

    /**
     * The event map for the model.
     *
     * @var array<string, string>
     */
    protected $dispatchesEvents = [
        'created' => RecommendationCreated::class,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'trip_id',
        'chat_session_id',
        'user_id',
        'recommendation_type',
        'source',
        'data',
        'confidence_score',
        'status',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'data' => 'array',
            'confidence_score' => 'decimal:2',
        ];
    }

    /**
     * Get the trip this recommendation belongs to.
     */
    public function trip()
    {
        return $this->belongsTo(Trip::class);
    }

    /**
     * Get the chat session that generated this recommendation.
     */
    public function chatSession()
    {
        return $this->belongsTo(ChatSession::class);
    }

    /**
     * Get the user who suggested this (if user-generated).
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the itinerary item created from this recommendation.
     */
    public function itineraryItem()
    {
        return $this->hasOne(ItineraryItem::class, 'recommendation_id');
    }

    /**
     * Scope a query to only include recommendations of a specific type.
     */
    public function scopeType($query, string $type)
    {
        return $query->where('recommendation_type', $type);
    }

    /**
     * Scope a query to only include recommendations with a specific status.
     */
    public function scopeStatus($query, string $status)
    {
        return $query->where('status', $status);
    }

    /**
     * Scope a query to only include pending recommendations.
     */
    public function scopePending($query)
    {
        return $query->where('status', 'pending');
    }

    /**
     * Scope a query to only include accepted recommendations.
     */
    public function scopeAccepted($query)
    {
        return $query->where('status', 'accepted');
    }

    /**
     * Scope a query to filter by source.
     */
    public function scopeSource($query, string $source)
    {
        return $query->where('source', $source);
    }

    /**
     * Accept the recommendation.
     */
    public function accept(): void
    {
        $this->update(['status' => 'accepted']);
    }

    /**
     * Reject the recommendation.
     */
    public function reject(): void
    {
        $this->update(['status' => 'rejected']);
    }

    /**
     * Mark as modified.
     */
    public function markAsModified(): void
    {
        $this->update(['status' => 'modified']);
    }

    /**
     * Check if recommendation is pending.
     */
    public function isPending(): bool
    {
        return $this->status === 'pending';
    }

    /**
     * Check if recommendation is accepted.
     */
    public function isAccepted(): bool
    {
        return $this->status === 'accepted';
    }

    /**
     * Check if recommendation was generated by AI.
     */
    public function isAiGenerated(): bool
    {
        return $this->source === 'ai_agent';
    }

    /**
     * Convert recommendation to itinerary item.
     */
    public function convertToItineraryItem(array $overrides = []): ItineraryItem
    {
        $itemData = array_merge([
            'trip_id' => $this->trip_id,
            'recommendation_id' => $this->id,
            'title' => $this->data['title'] ?? 'Untitled',
            'day_number' => $this->data['day_number'] ?? 1,
            'start_time' => $this->data['start_time'] ?? '09:00',
            'end_time' => $this->data['end_time'] ?? '10:00',
            'place_id' => $this->data['place_id'] ?? null,
            'note' => $this->data['note'] ?? null,
            'estimated_cost' => $this->data['estimated_cost'] ?? null,
        ], $overrides);

        $item = ItineraryItem::create($itemData);
        $this->accept();

        return $item;
    }
}
